# Generated by Django 5.0.3 on 2024-03-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_date_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='date_new',
        ),
    ]
