# Generated by Django 5.0.3 on 2024-03-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_remove_measurement_date_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='location',
            new_name='description',
        ),
    ]
